# Generated by Django 5.2.7 on 2025-10-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='items', to='api.customer'),
        ),
    ]
