# Generated by Django 5.2.7 on 2025-10-28 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_role_customer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity purchased')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at the time of purchase', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price (quantity * unit_price)', max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of purchase')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer who made the purchase', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='api.customer')),
                ('item', models.ForeignKey(help_text='Item that was purchased', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_history', to='api.item')),
            ],
            options={
                'verbose_name_plural': 'Purchase Histories',
                'ordering': ['-purchase_date'],
                'indexes': [models.Index(fields=['-purchase_date'], name='api_purchas_purchas_b9bfd3_idx'), models.Index(fields=['customer', '-purchase_date'], name='api_purchas_custome_a63ce9_idx')],
            },
        ),
    ]
