# Generated by Django 5.2.7 on 2025-10-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_purchasehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per unit', max_digits=10),
        ),
    ]
